version: "3.9"

services:
  postgres:
    image: postgres:11.2-alpine
    container_name: kanban_backend
    restart: always
    volumes:
      - ../../var/pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"


  backend_service:
    build: .   # relative to docker-compose
    volumes:
      - .:/app  # mount point
    ports:
      - 5001:8001 # host:container
    depends_on:
      - postgres